export default {
    HTTP_SUCCESS_OK: 200,
    HTTP_CREATED: 201,
    HTTP_NO_CONTENT: 204,
    HTTP_BAD_REQUEST: 400,
    HTTP_LOGIN_EMAIL: 403,
    HTTP_FAILED_SIX_MONTH: 402,
    HTTP_UNAUTHORIZED: 401,
    HTTP_CONFLICT: 409,
    HTTP_PASSWORD_NOMATCH: 420,
    HTTP_UNPROCESSABLE_ENTITY: 422,
    HTTP_INTERNAL_SERVER_ERROR: 500,
    HTTP_REQUESTED_RESOURCE_NOT_FOUND: 404,
    HTTP_PRECONDITION_FAILED: 412,
    HTTP_NOPARTICIPATIONRECRUITMENTS: 402
}

